---
name: Conductor Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 * * *
    
permissions: write-all

env:
  CONDUCTOR_URL: https://github.com/Netflix/conductor
  CONDUCTOR_BRANCH: main
  CONDUCTOR_BUILD_BY: 330372+lewis-green-bot[bot]@users.noreply.github.com
  CONDUCTOR_BUILD_TYPE: nightly
  REGISTRY: ghcr.io
  IMAGE_NAME_SERVER: conductor-server
  IMAGE_NAME_UI: conductor-ui

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        id: generate-token
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Setup variables
        id: vars
        run: |
          build_date=$(date +%Y%m%d%H%M)
          echo "tag-name=${{ env.CONDUCTOR_BUILD_TYPE }}-${build_date}" >> "$GITHUB_OUTPUT"

      - name: Clone conductor
        run: git clone -b ${{ env.CONDUCTOR_BRANCH }} --single-branch ${{ env.CONDUCTOR_URL }}

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push server Docker image (SERVER)
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: conductor
          file: conductor/docker/server/Dockerfile
          push: true          
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_SERVER }}:latest
          labels: ${{ steps.meta_server.outputs.labels }}

      - name: Build and push server Docker image (UI)
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: conductor
          file: conductor/docker/ui/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME_UI }}:latest
          labels: ${{ steps.meta_ui.outputs.labels }}
